on:
  push:

jobs:
  publish:
    name: Publish
    runs-on: docker
    env:
      NPM_TOKEN: ${{secrets.OWNER_TOKEN}}
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6
      - uses: https://github.com/oven-sh/setup-bun@v2
      - run: bun i
      - run: bun run build
      - run: bun run generate-types
      - run: bun publish -p --access public