on:
  push:

jobs:
  publish:
    name: Publish
    runs-on: docker
    steps:
      - name: Configure NPM registry
        run: |
          npm config set @test:registry ${{github.SERVER_URL}}/api/packages/{owner}/npm/
          npm config set "//forgejo.app.jumpdrive.dev/api/packages/{owner}/npm/:_authToken=${{secrets.OWNER_TOKEN}}"
      - uses: https://code.forgejo.org/actions/checkout@v6
      - uses: https://github.com/oven-sh/setup-bun
      - run: bun i


